apiVersion: v1
kind: Service
metadata:
    name: charthub-svc
spec:
    selector:
        app: charthub
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
        #   nodePort: 32000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: charthub-deployment
    labels:
        app: charthub
spec:
    replicas: 2
    selector:
        matchLabels:
            app: charthub
    template:
        metadata:
            labels:
                app: charthub
        spec:
            containers:
                - name: charthub-server
                  image: 'gdsoumya/charthub_go'
                - name: charthub-client
                  image: 'gdsoumya/charthub_nginx'
