export const SET_FILTER = "SET_FILTER";
export const GET_CHARTS = "GET_CHARTS";
export const LOAD_CHARTS_LOADING = 'REDUX_THUNK_LOAD_CHARTS_LOADING';
export const LOAD_CHARTS_SUCCESS = 'REDUX_THUNK_LOAD_CHARTS_SUCCESS';
export const LOAD_CHARTS_ERROR = 'REDUX_THUNK_LOAD_USERS_ERROR';
