export const SET_FILTER = "SET_FILTER";
export const GET_CHARTS = "GET_CHARTS";
export const LOAD_CHARTS_LOADING = 'REDUX_THUNK_LOAD_CHARTS_LOADING';
export const LOAD_CHARTS_SUCCESS = 'REDUX_THUNK_LOAD_CHARTS_SUCCESS';
export const LOAD_CHART_SUCCESS = 'REDUX_THUNK_LOAD_CHART_SUCCESS';
export const LOAD_CHARTS_ERROR = 'REDUX_THUNK_LOAD_CHARTS_ERROR';
export const LOAD_CHARTS_BY_ID_LOADING = 'REDUX_THUNK_LOAD_CHART_BY_ID'
export const GET_CHART = 'GET_CHART'
