export const LOAD_VERSION_SUCCESS = 'GET_VERSIONS'
export const LOAD_CHARTS_SUCCESS = 'GET_CHARTS';
export const LOAD_CHART_SUCCESS = 'GET_CHART';
export const FILTER_CHARTS_ON_SEARCH = 'FILTER_CHARTS_ON_SEARCH';
export const FILTER_CHARTS_BY_FILTERS = 'FILTER_CHARTS_BY_FILTERS';
export const LOAD_ANALYTICS_DATA = 'LOAD_ANALYTICS_DATA';
export const LOAD_GITHUB_STARS = "LOAD_GITHUB_STARS"
